name: Go Http NetHttp

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: ['http/go/nethttp/**', '.github/workflows/**']
  pull_request:
    paths: ['http/go/nethttp/**', '.github/workflows/**']

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      relativePath: ./http/go/nethttp
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.2'
      - name: Install dependencies
        run: go install
        working-directory: ${{ env.relativePath }}
      - name: Build SDK project
        run: go build
        working-directory: ${{ env.relativePath }}
